default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
  redis:
    host: localhost
    port: 6379
    db: 0
    options:
      namespace: blog-app-dev

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

staging:
  <<: *default
  database: blog_app_staging

production:
  <<: *default
  database: blog_app_production
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
